/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FilterImport } from './routes/filter'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FilterRoute = FilterImport.update({
  id: '/filter',
  path: '/filter',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/filter': {
      id: '/filter'
      path: '/filter'
      fullPath: '/filter'
      preLoaderRoute: typeof FilterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/filter': typeof FilterRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/filter': typeof FilterRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/filter': typeof FilterRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/filter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/filter'
  id: '__root__' | '/' | '/filter'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilterRoute: typeof FilterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilterRoute: FilterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/filter"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/filter": {
      "filePath": "filter.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
